server:
  port: ${PORT:8080}

spring:
  application:
    name: apiReactiva

  r2dbc:
    host: ${SPRING_R2DBC_HOST:localhost}
    port: ${SPRING_R2DBC_PORT:5432}
    database: ${SPRING_R2DBC_DATABASE:productdb}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG